[package]
name = "cubacadabra-builder"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glam = "0.30"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
sha2 = "0.10"
tempfile = "3"
zip = { version = "2", default-features = false, features = ["deflate", "time"] }
