use crate::{GeometryInstance, ImportOptions, ReferenceScene, load_reference};
use cubacadabra_scene::{AuthoringNode, AuthoringScene, EditorMetadata, SourceMetadata, Transform};
use glam::{EulerRot, Mat3, Quat};
use rbx_dom_weak::types::{Attributes, CFrame, Color3, Enum, Matrix3, Variant, Vector3};
use rbx_dom_weak::{Instance, InstanceBuilder, WeakDom, types::Ref, ustr};
use serde_json::{Value, json};
use sha2::{Digest, Sha256};
use std::{
    collections::{BTreeMap, BTreeSet, HashMap},
    fs::{self, File},
    io::{BufReader, BufWriter, Write},
    path::{Path, PathBuf},
};

const GENERATED_BY: &str = "cubacadabra-roblox-interchange";
const INTERACTION_TARGET_CFRAME: &str = "CubacadabraTargetCFrame";
const INTERACTION_TARGET_SIZE: &str = "CubacadabraTargetSize";
const INTERACTION_TWEEN_DURATION: &str = "CubacadabraTweenDuration";
const INTERACTION_SCRIPT: &str = r#"-- Generated by Cubacadabra's Roblox exporter.
local TweenService = game:GetService("TweenService")
local container = script.Parent

local function touchedByCharacter(hit)
	local ancestor = hit.Parent
	while ancestor and ancestor ~= workspace do
		if ancestor:IsA("Model") and ancestor:FindFirstChildOfClass("Humanoid") then
			return true
		end
		ancestor = ancestor.Parent
	end
	return false
end

local function connect(part)
	local targetCFrame = part:GetAttribute("CubacadabraTargetCFrame")
	local targetSize = part:GetAttribute("CubacadabraTargetSize")
	local duration = part:GetAttribute("CubacadabraTweenDuration")
	if typeof(targetCFrame) ~= "CFrame" or typeof(targetSize) ~= "Vector3" or typeof(duration) ~= "number" then
		return
	end

	local claimed = false
	part.Touched:Connect(function(hit)
		if claimed or not touchedByCharacter(hit) then
			return
		end
		claimed = true
		part.CanTouch = false
		TweenService:Create(
			part,
			TweenInfo.new(duration, Enum.EasingStyle.Quad, Enum.EasingDirection.Out),
			{ CFrame = targetCFrame, Size = targetSize }
		):Play()
	end)
end

for _, descendant in ipairs(container:GetDescendants()) do
	if descendant:IsA("BasePart") then
		connect(descendant)
	end
end
"#;

struct InteractionVisualExport {
    parts: Vec<InstanceBuilder>,
    fully_scripted: bool,
    scripted_parts: usize,
}

#[derive(Clone, Copy)]
struct InteractionTween {
    target_position: [f32; 3],
    target_size: [f32; 3],
    target_rotation: [f32; 3],
    duration: f32,
}

#[derive(Clone, Debug, PartialEq)]
pub struct RobloxAuthoringImport {
    pub scene: AuthoringScene,
    pub import_root_id: String,
    pub source_sha256: String,
    pub source_instances: usize,
    pub editable_parts: usize,
    pub preserved_instances: usize,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct RobloxExportReport {
    pub updated_parts: usize,
    pub added_parts: usize,
    pub preserved_instances: usize,
    pub omitted_nodes: usize,
    pub warnings: Vec<String>,
}

/// Merge the editable subset of a Roblox XML place into a native authoring
/// scene. The original XML remains the preservation layer and is referenced by
/// a project-relative path recorded on every generated node.
pub fn import_roblox_authoring_scene(
    place_path: impl AsRef<Path>,
    base_scene: &AuthoringScene,
    source_file: &str,
) -> Result<RobloxAuthoringImport, String> {
    base_scene.validate()?;
    let place_path = place_path.as_ref();
    let reference = load_reference(&ImportOptions {
        place_path: place_path.to_path_buf(),
        terrain_path: None,
        project_path: None,
        output_path: PathBuf::new(),
    })?;
    merge_reference(reference, base_scene, source_file, place_path)
}

fn merge_reference(
    reference: ReferenceScene,
    base_scene: &AuthoringScene,
    source_file: &str,
    place_path: &Path,
) -> Result<RobloxAuthoringImport, String> {
    let mut scene = base_scene.clone();
    let parent_id = scene
        .nodes
        .iter()
        .find(|node| node.parent_id.is_none())
        .map(|node| node.id.clone())
        .ok_or_else(|| "authoring scene has no root node for the Roblox import".to_owned())?;
    let import_id = short_hash(&reference.source.place.sha256);
    scene.nodes.retain(|node| {
        node.source
            .as_ref()
            .and_then(|source| source.properties.get("importId"))
            .and_then(Value::as_str)
            != Some(import_id.as_str())
    });

    let import_root_id = unique_id(&scene, &format!("roblox-import-{import_id}"));
    let source_root_id = unique_id(&scene, &format!("roblox-source-{import_id}"));
    let display_name = Path::new(&reference.source.place.name)
        .file_stem()
        .and_then(|stem| stem.to_str())
        .filter(|stem| !stem.is_empty())
        .unwrap_or("Roblox Place");
    let dom = decode_xml(place_path)?;
    let dom_paths = instance_refs_by_path(&dom)?;
    let promoted = reference
        .geometry
        .iter()
        .filter(|geometry| {
            promotable_part(geometry) && crate::is_roblox_workspace_path(&reference, &geometry.path)
        })
        .collect::<Vec<_>>();
    let promoted_paths = promoted
        .iter()
        .map(|geometry| geometry.path.as_str())
        .collect::<BTreeSet<_>>();
    let preserved_instances = reference.instances.len().saturating_sub(promoted.len());

    scene.nodes.push(AuthoringNode {
        id: import_root_id.clone(),
        parent_id: Some(parent_id.clone()),
        name: display_name.to_owned(),
        transform: Transform::default(),
        components: BTreeMap::new(),
        editor: EditorMetadata::default(),
        source: Some(source_metadata(
            "ImportRoot",
            None,
            source_file,
            &import_id,
            BTreeMap::from([
                ("compatibility".to_owned(), json!("native-and-preserved")),
                ("editableParts".to_owned(), json!(promoted.len())),
                ("preservedInstances".to_owned(), json!(preserved_instances)),
            ]),
        )),
    });
    scene.nodes.push(AuthoringNode {
        id: source_root_id,
        parent_id: Some(import_root_id.clone()),
        name: "Preserved Roblox Source".to_owned(),
        transform: Transform::default(),
        components: BTreeMap::new(),
        editor: EditorMetadata {
            visible: true,
            locked: true,
            lock_reason: Some(
                "Unsupported Roblox objects are preserved in the source XML and exported unchanged"
                    .to_owned(),
            ),
        },
        source: Some(source_metadata(
            "SourceArchive",
            None,
            source_file,
            &import_id,
            BTreeMap::from([
                (
                    "sourceSha256".to_owned(),
                    json!(reference.source.place.sha256),
                ),
                ("instanceCount".to_owned(), json!(reference.instances.len())),
                ("preservedInstances".to_owned(), json!(preserved_instances)),
            ]),
        )),
    });

    let instances = reference
        .instances
        .iter()
        .map(|instance| (instance.path.as_str(), instance))
        .collect::<BTreeMap<_, _>>();
    let mut group_paths = BTreeSet::new();
    for geometry in &promoted {
        let mut ancestor = geometry.parent_path.as_str();
        while let Some(instance) = instances.get(ancestor) {
            if matches!(instance.class.as_str(), "Model" | "Folder") {
                group_paths.insert(instance.path.clone());
            }
            if instance.class == "Workspace" || instance.parent_path.is_empty() {
                break;
            }
            ancestor = &instance.parent_path;
        }
    }
    let mut group_paths = group_paths.into_iter().collect::<Vec<_>>();
    group_paths.sort_by_key(|path| (path.split('/').count(), path.clone()));
    let mut group_ids = BTreeMap::new();
    for path in group_paths {
        let Some(instance) = instances.get(path.as_str()) else {
            continue;
        };
        let id = unique_id(&scene, &format!("roblox-group-{}", short_hash(&path)));
        let parent = group_ids
            .get(instance.parent_path.as_str())
            .cloned()
            .unwrap_or_else(|| import_root_id.clone());
        group_ids.insert(path.clone(), id.clone());
        let has_unrepresented_descendant = reference.instances.iter().any(|candidate| {
            candidate.path.starts_with(&format!("{}/", instance.path))
                && !promoted_paths.contains(candidate.path.as_str())
                && !matches!(candidate.class.as_str(), "Model" | "Folder")
        });
        scene.nodes.push(AuthoringNode {
            id,
            parent_id: Some(parent),
            name: instance.name.clone(),
            transform: Transform::default(),
            components: BTreeMap::new(),
            editor: EditorMetadata {
                visible: true,
                locked: has_unrepresented_descendant,
                lock_reason: has_unrepresented_descendant.then_some(
                    "This Roblox group contains preserved objects that Studio cannot transform safely yet"
                        .to_owned(),
                ),
            },
            source: Some(source_metadata(
                &instance.class,
                Some(&instance.path),
                source_file,
                &import_id,
                BTreeMap::from([("representation".to_owned(), json!("native-group"))]),
            )),
        });
    }

    for geometry in promoted {
        if !promoted_paths.contains(geometry.path.as_str()) {
            continue;
        }
        let id = unique_id(
            &scene,
            &format!("roblox-part-{}", short_hash(&geometry.path)),
        );
        let parent = group_ids
            .get(&geometry.parent_path)
            .cloned()
            .unwrap_or_else(|| import_root_id.clone());
        let shape = if geometry.shape == Some(0) {
            "sphere"
        } else {
            "box"
        };
        let mut components = BTreeMap::from([(
            "primitive".to_owned(),
            json!({
                "shape": shape,
                "size": geometry.size,
                "color": source_color(geometry.color),
                "collidable": geometry.can_collide,
                "castShadow": geometry.cast_shadow,
            }),
        )]);
        if geometry.can_collide && shape == "box" {
            components.insert("collision".to_owned(), json!({"kind": "box"}));
        }
        let source_property = |name: &str| {
            dom_paths
                .get(geometry.path.as_str())
                .and_then(|reference| dom.get_by_ref(*reference))
                .is_some_and(|instance| instance.properties.contains_key(&ustr(name)))
        };
        scene.nodes.push(AuthoringNode {
            id,
            parent_id: Some(parent),
            name: geometry.name.clone(),
            transform: Transform {
                position: geometry.transform.position,
                rotation: crate::roblox_source_rotation_to_euler(geometry.transform.rotation),
                scale: [1.0; 3],
            },
            components,
            editor: EditorMetadata::default(),
            source: Some(source_metadata(
                &geometry.class,
                Some(&geometry.path),
                source_file,
                &import_id,
                BTreeMap::from([
                    ("representation".to_owned(), json!("native-primitive")),
                    ("sourceAnchored".to_owned(), json!(geometry.anchored)),
                    ("sourceMaterial".to_owned(), json!(geometry.material.name)),
                    (
                        "sourceMaterialValue".to_owned(),
                        json!(geometry.material.value),
                    ),
                    (
                        "sourceHasColor".to_owned(),
                        json!(source_property("Color") || source_property("Color3uint8")),
                    ),
                    (
                        "sourceHasCanCollide".to_owned(),
                        json!(source_property("CanCollide")),
                    ),
                    (
                        "sourceHasCastShadow".to_owned(),
                        json!(source_property("CastShadow")),
                    ),
                ]),
            )),
        });
    }
    scene.validate()?;
    Ok(RobloxAuthoringImport {
        scene,
        import_root_id,
        source_sha256: reference.source.place.sha256,
        source_instances: reference.instances.len(),
        editable_parts: promoted_paths.len(),
        preserved_instances,
    })
}

fn source_metadata(
    class: &str,
    path: Option<&str>,
    source_file: &str,
    import_id: &str,
    mut properties: BTreeMap<String, Value>,
) -> SourceMetadata {
    properties.insert("generatedBy".to_owned(), json!(GENERATED_BY));
    properties.insert("sourceFile".to_owned(), json!(source_file));
    properties.insert("importId".to_owned(), json!(import_id));
    SourceMetadata {
        format: "roblox".to_owned(),
        class: Some(class.to_owned()),
        path: path.map(str::to_owned),
        properties,
    }
}

fn promotable_part(geometry: &GeometryInstance) -> bool {
    crate::validate_roblox_native_part(geometry).is_ok()
}

pub fn roblox_source_file(scene: &AuthoringScene) -> Option<&str> {
    roblox_source_files(scene).into_iter().next()
}

pub fn roblox_source_files(scene: &AuthoringScene) -> Vec<&str> {
    let mut seen = BTreeSet::new();
    scene
        .nodes
        .iter()
        .filter_map(|node| {
            node.source
                .as_ref()
                .filter(|source| source.format == "roblox")?
                .properties
                .get("sourceFile")?
                .as_str()
        })
        .filter(|source_file| seen.insert(*source_file))
        .collect()
}

/// Export a Roblox XML place. When `preserved_source` is present, the original
mod export;
mod export_helpers;

pub use export::{write_roblox_place, write_roblox_place_with_manifest};
use export_helpers::{decode_xml, instance_refs_by_path, short_hash, source_color, unique_id};

#[cfg(test)]
mod tests;
