name: Cross-repository compatibility

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:
    inputs:
      tools_ref:
        description: "Tools ref to test"
        required: false
        default: main
      rust_ref:
        description: "Rust ref to test"
        required: false
        default: main
      web_ref:
        description: "Web ref to test"
        required: false
        default: main
      examples_ref:
        description: "Examples ref to test"
        required: false
        default: main
      studio_ref:
        description: "Studio ref to test"
        required: false
        default: main
      desktop_ref:
        description: "Desktop ref to test"
        required: false
        default: main
      ios_ref:
        description: "iOS app ref to test"
        required: false
        default: main
      android_ref:
        description: "Android app ref to test"
        required: false
        default: main

jobs:
  compatibility:
    uses: ./.github/workflows/compatibility-reusable.yml
    with:
      tools_repository: ${{ github.repository }}
      tools_ref: ${{ inputs.tools_ref || github.sha }}
      rust_ref: ${{ inputs.rust_ref || 'main' }}
      web_ref: ${{ inputs.web_ref || 'main' }}
      examples_ref: ${{ inputs.examples_ref || 'main' }}
      studio_ref: ${{ inputs.studio_ref || 'main' }}
      desktop_ref: ${{ inputs.desktop_ref || 'main' }}
      ios_ref: ${{ inputs.ios_ref || 'main' }}
      android_ref: ${{ inputs.android_ref || 'main' }}
